### ISSUE TITLE
emoji位置支持配置

### ISSUE THREAD

**Issue by vincentzyc** [UvDream/git-commit-lint-vscode#11]
感谢作者，插件很好用，提个小建议，emoji位置支持配置，或者默认模板支持配置，例如： < emoji >< type >:

**Comment by UvDream** [comment]
收到!等有时间做好,会在这个issue里面回复你

**Comment by UvDream** [comment]
今天2.0版本支持

**Comment by UvDream** [comment]
> 感谢作者，插件很好用，提个小建议，emoji位置支持配置，或者默认模板支持配置，例如： < emoji >< type >:

2.0已上线，可以自定义

**Comment by vincentzyc** [comment]
已更新，辛苦啦，点赞
