### ISSUE TITLE
emoji图标位置配置

### ISSUE THREAD

**Issue by MARIOMARUI** [UvDream/git-commit-lint-vscode#14]
默认start 表示图标在前 描述文字在后
可选择end 表示图标在后 描述文字在前

**Comment by UvDream** [comment]
目前这个版本不考虑

**Comment by hks2002** [comment]
```
{
        emoji: "feat✨:",
        code: "feat: ",
        description: "引入新功能",
        name: "新功能"
    }
```
改为
```
{
        emoji: "feat: ✨",
        code: "feat: ",
        description: "引入新功能",
        name: "新功能"
    }
```
就可以避免@commitlint/config-conventional 检验不通过的问题

**Comment by UvDream** [comment]
> ```
> {
>         emoji: "feat✨:",
>         code: "feat: ",
>         description: "引入新功能",
>         name: "新功能"
>     }
> ```
> 
> 改为
> 
> ```
> {
>         emoji: "feat: ✨",
>         code: "feat: ",
>         description: "引入新功能",
>         name: "新功能"
>     }
> ```
> 
> 就可以避免@commitlint/config-conventional 检验不通过的问题

如果你们能接受的话,可以改成这样的

**Comment by UvDream** [comment]
> ```
> {
>         emoji: "feat✨:",
>         code: "feat: ",
>         description: "引入新功能",
>         name: "新功能"
>     }
> ```
> 
> 改为
> 
> ```
> {
>         emoji: "feat: ✨",
>         code: "feat: ",
>         description: "引入新功能",
>         name: "新功能"
>     }
> ```
> 
> 就可以避免@commitlint/config-conventional 检验不通过的问题

不过这个有不带图标模式

**Comment by hks2002** [comment]
变更后，将图标模式的逻辑放到 描述的后半部分，不喜欢带图标就不带图标，喜欢带的就带上，保持前半部分`feat:`这种不带图标的风格， commitlint检验就不会不通过了， 当前默认带图标的模式， 检验是会报错的

**Comment by UvDream** [comment]
> 变更后，将图标模式的逻辑放到 描述的后半部分，不喜欢带图标就不带图标，喜欢带的就带上，保持前半部分`feat:`这种不带图标的风格， commitlint检验就不会不通过了， 当前默认带图标的模式， 检验是会报错的

<img width="601" alt="image" src="https://user-images.githubusercontent.com/33121872/215303451-6f6eb10e-02d3-451e-8094-a1a682367135.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/33121872/215303461-7d713585-09c1-4a11-82c4-f8373d3627ad.png">
默认是带表情的,也可以切换为不带表情的

**Comment by hks2002** [comment]
要带emoji还要能commintlint, 两个都是硬需求

**Comment by UvDream** [comment]
> 要带emoji还要能commintlint, 两个都是硬需求

2.0版本已上线，可以自定义

**Comment by horizon188** [comment]
{
      "emoji": "✨",
      "type": "feat",
      "name": "引入新功能",
      "description": "新功能"
    },

**Comment by horizon188** [comment]
这个怎么改？

**Comment by horizon188** [comment]
2.20版本
