### ISSUE TITLE
默认不应该将已经填写好的 commit 信息清空

### ISSUE THREAD

**Issue by heartacker** [UvDream/git-commit-lint-vscode#15]
我已经写好了commit 信息之后，结果点击按钮直接就清空了我的填写好的信息了。

呜呜呜。应该追加而不是清空

**Comment by UvDream** [comment]
点击对号么

**Comment by niusz** [comment]
这是使用的问题吧

**Comment by heartacker** [comment]
> 点击对号么

点击表情的图标

**Comment by UvDream** [comment]
> > 点击对号么
> 
> 点击表情的图标

你的意思你填完信息再次点击表情希望只替换前缀的意思吧

**Comment by heartacker** [comment]
对

**Comment by UvDream** [comment]
> 对

考虑大部分人不能这么更改,等下次重构的时候可以加个用户配置,让用户选择
