### ISSUE TITLE
输入文字在输入tag会清空已输入内容

### ISSUE THREAD

**Issue by cgrain1998** [UvDream/git-commit-lint-vscode#18]
如果先输入文字在输入表情会清除我已经输入的文字，能不能在前面追加就好？
![image](https://user-images.githubusercontent.com/35121432/217995779-a9d1e0b5-38da-4097-8131-8c5ba6ba56f6.png)

并且如果我又两个仓库，我输入的是第二个tab选择表情后光标在第一个
![image](https://user-images.githubusercontent.com/35121432/217995991-ecad8376-4f68-4ec5-a8f2-3d48fcc7e4a3.png)

**Comment by UvDream** [comment]
已解决
