### ISSUE TITLE
为什么点完标签，光标焦点自动到最前面了。。。

### ISSUE THREAD

**Issue by 672064406zerui** [UvDream/git-commit-lint-vscode#2]
测试测试docs📝  像这样  点完表情后，在打字出来就是这样的。

**Comment by UvDream** [comment]
这是个bug,下个版本修复

**Comment by UvDream** [comment]
这个bug已经修复了,请悉知

**Comment by 672064406zerui** [comment]
没新版本啊vscode

**Comment by UvDream** [comment]
你的vscode也要保持最新,然后试试就晓得了

**Comment by 672064406zerui** [comment]
情况依然那样，没解决啊。 1.44.2 最新的了

**Comment by UvDream** [comment]
![image](https://user-images.githubusercontent.com/33121872/81642456-01695500-9456-11ea-8124-5c556620c7f3.png)
我测试了其他电脑,都已经可以了,还有vscode已经1.45.0版本了,
