### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by niusz** [UvDream/git-commit-lint-vscode#22]
https://user-images.githubusercontent.com/30288073/225836617-fae26da3-9095-491d-bd8e-192eb343426c.mp4

点了按钮后，这个地方会收起来，之前不这样的
![image](https://user-images.githubusercontent.com/30288073/225836902-d203d965-a0ec-45f7-8e16-008e2ebd3a23.png)

**Comment by FreezeNow** [comment]
请问你的 VS Code 是什么版本？最新版VS Code 当只存在一个存储库时，是没有合拢存储库的按钮的
导致你这个问题的可能原因是：如果你有多个存储库，则会先合拢所有存储库，然后打开选择的存储库，但是现在存储库数量异常，导致打开了错误的存储库

**Comment by niusz** [comment]
我是最新的vscode Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No



在 2023-03-17 17:18:40，"FreezeNow" ***@***.***> 写道：

请问你的 VS Code 是什么版本？最新版VS Code 当只存在一个存储库时，是没有合拢存储库的按钮的
导致你这个问题的可能原因是：如果你有多个存储库，则会先合拢所有存储库，然后打开选择的存储库，但是现在存储库数量异常，导致打开了错误的存储库

**Comment by FreezeNow** [comment]
你可以等待修复，或者找到 设置>功能>源代码管理>Always Show Repositories，设为false（就是移除勾）
