### ISSUE TITLE
图标不显示

### ISSUE THREAD

**Issue by yellowsae** [UvDream/git-commit-lint-vscode#25]
VSCode 版本 版本: 1.83.0 

![image](https://github.com/UvDream/git-commit-lint-vscode/assets/58903178/ad2c3308-2677-408c-9a2a-e8d62d2feb2a)

**Comment by FreezeNow** [comment]
你要是着急的话，可以修改 C:\Users\用户名\.vscode\extensions\uvdream.git-commit-lint-vscode-2.1.0\static 目录下的 icon.svg 文件（light 主题修改 icon_light.svg），搜索 width 和 height，将 200 修改为 16，图标就会显示了。

**Comment by UvDream** [comment]
已发版，更新重启即可
