### ISSUE TITLE
能否和commitlint 结合使用呢？现在貌似不行

### ISSUE THREAD

**Issue by yan170772286** [UvDream/git-commit-lint-vscode#3]
现在图形生成的 不带冒号，所以不符合commitlint规范，能否出一版结合commitlint使用的

**Comment by UvDream** [comment]
好的,我考虑一下,感谢建议

**Comment by UvDream** [comment]
已经更新,如果还有啥新的想法可以提给我,之前不小心把这个项目issues关闭通知,也以为没啥人用我这个插件,这么久才看到,不好意思,现在开启通知了,会及时回复更新的

**Comment by UvDream** [comment]
切换方法是`F1`后输入`git commit lint switch`
