### ISSUE TITLE
关于最新版vscode中插件在源代码管理中图标出现的问题

### ISSUE THREAD

**Issue by HowieMen** [UvDream/git-commit-lint-vscode#4]
作者你好, 我在2020年7月14日更新到最新版本的vscode后, 发现在源代码管理里咱这个插件的图标消失不见了, 就是那个像雪花一样的图标, 期待你看到这条留言后能够修复这个问题, 十分感谢你

**Comment by UvDream** [comment]
vscode新版本就好了,是vscode新版本导致的
